package redisx

// command
const (
	// hash command
	HashHset         = "hset"
	HashHsetnx       = "hsetnx"
	HashHget         = "hget"
	HashHexists      = "hexists"
	HashHdel         = "hdel"
	HashHlen         = "hlen"
	HashHstrlen      = "hstrlen"
	HashHincrby      = "hincrby"
	HashHincrbyfloat = "hincrbyfloat"
	HashHmset        = "hmset"
	HashHmget        = "hmget"
	HashHkeys        = "hkeys"
	HashHvals        = "hvals"
	HashHgetall      = "hgetall"

	// zset command
	ZsetZadd             = "zadd"
	ZsetZcard            = "zcard"
	ZsetZcount           = "zcount"
	ZsetZlexcount        = "zlexcount"
	ZsetZincrby          = "zincrby"
	ZsetZmscore          = "zmscore"
	ZsetZpopmax          = "zpopmax"
	ZsetZpopmin          = "zpopmin"
	ZsetZrange           = "zrange"
	ZsetZrangebyscore    = "zrangebyscore"
	ZsetZrank            = "zrank"
	ZsetZrem             = "zrem"
	ZsetZremrangebyrank  = "zremrangebyrank"
	ZsetZremrangebyscore = "zremrangebyscore"
	ZsetZrevrange        = "zrevrange"
	ZsetZrevrangebyscore = "zrevrangebyscore"
	ZsetZrevrank         = "zrevrank"
	ZsetZscore           = "zscore"
	ZsetZrandmember      = "zrandmember"

	// string command
	StringSet         = "set"
	StringSetex       = "setex"
	StringPsetex      = "psetex"
	StringSetrange    = "setrange"
	StringGet         = "get"
	StringGetrange    = "getrange"
	StringGetset      = "getset"
	StringIncr        = "incr"
	StringIncrby      = "incrby"
	StringIncrbyfloat = "incrbyfloat"
	StringDecr        = "decr"
	StringDecrby      = "decrby"
	StringStrlen      = "strlen"
	StringAppend      = "append"
	StringMget        = "mget"
	StringMset        = "mset"
	StringMsetnx      = "msetnx"

	// list command
	ListLpush      = "lpush"
	ListLpushx     = "lpushx"
	ListLrange     = "lrange"
	ListLrem       = "lrem"
	ListLset       = "lset"
	ListLtrim      = "ltrim"
	ListRpop       = "rpop"
	ListRpoplpush  = "rpoplpush"
	ListRpush      = "rpush"
	ListRpushx     = "rpushx"
	ListBlpop      = "blpop"
	ListBrpop      = "brpop"
	ListBrpoplpush = "brpoplpush"
	ListLindex     = "lindex"
	ListLinsert    = "linsert"
	ListLlen       = "llen"
	ListLpop       = "lpop"

	// set command
	SetSadd        = "sadd"
	SetScard       = "scard"
	SetSdiff       = "sdiff"
	SetSdiffstore  = "sdiffstore"
	SetSinter      = "sinter"
	SetSinterstore = "sinterstore"
	SetSismember   = "sismember"
	SetSmembers    = "smembers"
	SetSmove       = "smove"
	SetSpop        = "spop"
	SetSrandmember = "srandmember"
	SetSrem        = "srem"
	SetSunion      = "sunion"
	SetSunionstore = "sunionstore"

	// keys command
	KeyDel       = "del"
	KeyExists    = "exists"
	KeyExpire    = "expire"
	KeyExpireat  = "expireat"
	KeyKeys      = "keys"
	KeyPersist   = "persist"
	KeyPexpire   = "pexpire"
	KeyPexpireat = "pexpireat"
	KeyPttl      = "pttl"
	KeyRandomkey = "randomkey"
	KeyTouch     = "touch"
	KeyTTL       = "ttl"
	KeyType      = "type"
)

const (
	PipeLineCmdStatValZero = 0
	PipeLineCmdStatVal     = 1
)
